apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: inference_graph-deploy-all-run
  namespace: tekton-operator
spec:
  serviceAccountName: physarum-kubernetes
  taskRef:
    name: inference_graph-deploy-all
